sigstore/policy-controller

.ko.yaml

- update ko configuration
n/a
```release-note
NONE
```

update ko configuration

---

.github/workflows/build.yaml
.github/workflows/cut-release.yml

update gcp service account

---

config/300-clusterimagepolicy.yaml

Add missing conversion definition as part of the CR definition.
Fixes https://github.com/sigstore/policy-controller/issues/35
```release-note
Add missing conversion strategy to the CR definition.
```

fix: add missing conversion to CRD

---

pkg/webhook/validator.go

If a secret is not set during the installation, then the verification should be done against the fulcio root. Generally, we assume the ClusterImagePolicy defines a key to verify against the signed images.
I keep the secret as an installation flag to keep backwards compatibility. 
Fixes
```release-note
chore: do not fail to verify signed images if the --secret-name flag is not set during the installation.
```

chore: skip secret not found

---

cmd/tester/main.go

Validate CIP after defaulting and before using it to catch mistakes in authoring a CIP.

Validate CIP before using it.

---

CHANGELOG.md

Preparing release for v0.1.0 and updated the release notes since the creation of the repo.

Update CHANGELOG to reflect changes since creating the repository.

---

release/cloudbuild.yaml

- update go builder and cosign
`n/a`
`n/a`

update go builder and cosign

---

release/cloudbuild.yaml

- fix path in cloudbuild
`n/a`
`n/a`

fix path in cloudbuild

---

config/300-clusterimagepolicy.yaml
pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
pkg/apis/policy/v1beta1/clusterimagepolicy_types.go

I added some missing documentation about the purpose of each field in the ClusterImagePolicy definition.

chore: add golang documentation to the api types

---

README.md

I am adding an intro to the Policy controller in our README.

chore: add more context to the README

---

Makefile

I found couple of inconsistent references to our cosign Makefile.

fix: Makefile wrong targets

---

README.md

- add documentation about release cadence
Fixes: #71

add documentation about release cadence

---

pkg/webhook/validator_result.go

While debugging #130 we realized that there's some cruft there, so let's get rid of it to make things more readable.

use omit-empty to make results more readable and concise.

---

README.md

Document the issuerRegExp and subjectRegExp fields. 
https://github.com/sigstore/sigstore-website/pull/208

Add issuerRegExp and subjectRegExp fields to doc.

---

pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go

related to #107 
I am just checking what we want to enforce with this Draft pull request, some e2e tests need to be adapted to this new validation.

chore: require setting the identity - issuer and subject

---

.github/workflows/kind-cluster-image-policy-scaling.yaml
.github/workflows/kind-cluster-image-policy-with-attestations.yaml
.github/workflows/kind-cluster-image-policy.yaml

Use scaffolding v0.4.3 for e2e testing.

Use scaffolding v0.4.3. Remove unused KNATIVE_VERSION env var.

---

.github/workflows/policy-tester-examples.yml

Add --type spdxjson to verify-attestation since newer cosign has a bug fix that fails (as it should) this test.
This should then fix #156 

Add --type spdxjson to verify-attestation

---

.github/workflows/kind-cluster-image-policy.yaml
cmd/webhook/main.go
config/webhook.yaml
test/e2e_test_cluster_image_policy.sh
test/e2e_test_cluster_image_policy_with_attestations.sh
test/e2e_test_cluster_with_scalable.sh
test/kustomize/kustomization.yaml

Add two new flags that you can use to specify how to initialize TUF root.
--tuf-mirror
--tuf-root
We then do equivalent of cosign initialize with those.
* Add two new flags that allow you to bring in a custom TUF root: --tuf-mirror and --tuf-root.
* DEPRECATED: Enviromental variables should be considered deprecated as the whole sigstore is moving everything to TUF.

Use TUF instead of env variables.

---

examples/policies/signed-by-github-actions.yaml

fix the test failure when we run the job on the main branch push
for reference: https://github.com/sigstore/policy-controller/runs/7880571441?check_suite_focus=true

fix keyless check

---

.github/workflows/release.yaml

- add missing action to install ko

add missing action to install ko

---

README.md

- add initial Support Policy documentation

add initial Support Policy documentation

---

.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/style.yaml
cmd/webhook/main.go
go.mod
go.sum

This fixes #90 by not unnecessarily getting invoked for status updates (which we handle but it's noisy in the logs) as well as for deletes. Until I get this wrangled into the upstream, this is just showing using my personal branch.
After this change, the new reconciled validatingwebhookconfiguration looks like this:
```
rules:
- apiGroups:
- ""
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- pods
scope: '*'
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- daemonsets
scope: '*'
- apiGroups:
- apps
apiVersions:
- v1
operations:
- CREATE
- UPDATE
resources:
- deployments
scope: '*'
```
Compared to previous:
```
rules:
- apiGroups:
- ""
apiVersions:
- v1
operations:
- CREATE
- UPDATE
- DELETE …
```

Fixes #90 by configuring webhook not to get called on status updates.

---

go.mod
go.sum

Signed-off-by: Kenny Leung <kleung@chainguard.dev>
bump sigstore/cosign to 1.11.1

bump sigstore/cosign to 1.11.1

---

.github/workflows/kind-cluster-image-policy.yaml
cmd/tester/main.go
config/300-clusterimagepolicy.yaml
config/webhook.yaml
go.mod
go.sum
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_defaults.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_defaults_test.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1beta1/clusterimagepolicy_defaults.go
pkg/apis/policy/v1beta1/clusterimagepolicy_defaults_test.go
pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
pkg/reconciler/testing/v1alpha1/clusterimagepolicy.go
pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
pkg/webhook/validator.go
pkg/webhook/validator_test.go
test/e2e_test_cluster_image_policy_with_warn.sh
test/testdata/policy-controller/e2e/cip-keyless-warn.yaml
test/testdata/policy-controller/invalid/invalid-mode.yaml
test/testdata/policy-controller/invalid/v1beta1-invalid-mode.yaml
test/testdata/policy-controller/valid/valid-policy.yaml

Fixes: #98 
Add `mode` field to CIP that allows you to specify 'warn' or 'enforce'. If warn specified the failed policies are returned as webhook warnings and won't block the admission.
* Fixes: #98 
* Add `mode` field to CIP that allows you to specify 'warn' or 'enforce'. If warn specified the failed policies are returned as webhook warnings and won't block the admission.
https://github.com/sigstore/sigstore-website/pull/215

Add warn mode for CIP.

---

.github/workflows/release.yaml

- fix order of the release steps

fix order of the release steps

---

.github/workflows/release.yaml
.gitignore

- ignore the credentials and setup gcloud

ignore the credentials and setup gcloud

---

README.md
test/testdata/policy-controller/valid/v1beta1-valid-policy.yaml
test/testdata/policy-controller/valid/valid-policy.yaml

README was using `subject`, with RegExp which requires
an exact match
Signed-off-by: Luke Hinds <lhinds@redhat.com>

Misleading docs on use of regexp

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/release.yaml

Signed-off-by: Jason Hall <jason@chainguard.dev>
Previously, https://github.com/sigstore/cosign/pull/2225
```release-note
NONE
```
cc @hectorj2f

upgrade setup-ko to point to new repo

---

README.md
cmd/webhook/main.go
config/webhook.yaml
pkg/webhook/validation.go
pkg/webhook/validator.go
pkg/webhook/validator_test.go
test/e2e_test_policy_controller.sh

This PR aims to remove the -secret-name flag and get rid off the deprecated behaviour (see more details here https://github.com/sigstore/policy-controller#deprecated-policy-controller-validation-behavior) that validated containers images against the fulcio root and the public key specified in the flag.
closes #222

Remove secret name flag

---

config/300-clusterimagepolicy.yaml
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
pkg/apis/signaturealgo/signature_digest.go
pkg/apis/signaturealgo/signature_digest_test.go
pkg/client/clientset/versioned/fake/register.go
pkg/client/clientset/versioned/scheme/register.go
pkg/reconciler/clusterimagepolicy/clusterimagepolicy.go
pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
pkg/webhook/validation.go
pkg/webhook/validator.go
pkg/webhook/validator_test.go
test/e2e_test_cluster_image_policy.sh
test/testdata/policy-controller/e2e/cip-key-hash-algorithm.yaml
test/testdata/policy-controller/invalid/v1beta1-invalid-hash-algo.yaml
test/testdata/policy-controller/valid/valid-policy-hash-algo-sha512.yaml
test/testdata/policy-controller/valid/valid-policy-hash-algo.yaml
third_party/VENDOR-LICENSE/github.com/aws/smithy-go/internal/sync/singleflight/LICENSE

This PR adds a new field to the `authority.key` element setting the signature hash algorithm, e.g. sha256, sha512
```
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
name: demo
spec:
images:
- glob: '**'
authorities:
- name: simplekey
key:
hashAlgorithm: sha256
data: |
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE80swOaWDTfEDEqQoc7zWZWWM8xaZ
TvYZCTJymLEl9hVgjBrCCoSbJ4QPncovTwyElYVuK1ajNDFovaensgl7QQ==
-----END PUBLIC KEY-----
```
The supported hash algorithms are defined in https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/options/signature_digest.go#L30.
related to https://github.com/sigstore/policy-controller/issues/234
I'll update our schema document with all the fields.

Add a new field to set the signature hash algorithm

---

pkg/webhook/validator.go
pkg/webhook/validator_test.go

Inspired by this comment: https://github.com/sigstore/policy-controller/pull/270#discussion_r982764535
Started refactoring the largish function into smaller pieces and added parallel container validation.
Fixes #272 
Also fix a bug where if requests get cancelled, we'd return before waiting for all goroutines to finish.
* Validate containers in parallel which will speed up webhook execution for resources with multiple containers.
* Fix an issue where if a context was cancelled before all validations finished, we did not wait for go routines to finish.

Validate containers in parallel.

---

pkg/apis/config/image_policies_test.go
pkg/apis/config/testdata/config-image-policies.yaml
pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
pkg/reconciler/testing/v1alpha1/clusterimagepolicy.go
pkg/webhook/cache.go
pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
pkg/webhook/nocache.go
pkg/webhook/validator.go

Start wiring up caching as per #278 that caches Policies against an image and more importantly against a particular version of a CIP. Need to make sure we're checking against the latest and greatest of the CIP, so add fields for those. At the moment doesn't do anything useful, as far as caching goes, but starting to see how it could look like.

Cache scaffolding

---

go.mod
go.sum

Bump sigstore dependencies to the latest available releases.
`Bump sigstore dependencies to the latest available releases.`

bump sigstore deps to latest

---

Makefile
README.md
cmd/api-docs/main.go
docs/api-types/index.md

We are currently missing any documentation related to the api docs and the purpose of each field.
Auto-generate API documentation for each ClusterImagePolicy field.

Add api docs generator

---

test/e2e_test_policy_controller.sh
test/testdata/fancy_from.Dockerfile
test/testdata/signed_manifest.yaml
test/testdata/single_stage.Dockerfile
test/testdata/unsigned_build_stage.Dockerfile
test/testdata/with_lowercase.Dockerfile

- update images to the new path
there are some tests that is using the old path, i will try to update those, did not made in this PR because they are failing and I will need more time to figure out

update images to the new path

---

.github/workflows/depsreview.yml

Signed-off-by: Bob Callaway <bcallaway@google.com>

switch to reusable workflow

---

pkg/webhook/cache.go
pkg/webhook/nocache.go
pkg/webhook/validator.go

We're just storing the CIP uid which doesn't give a descriptive information of which policy was evaluated. I suggest storing both uid and name, so we can give more detailed information of the results after evaluating a policy.
Add policy name to the cache fields.

Add policy name to the cache

---

.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy.yaml

Bumping scaffolding to fix our CI issues.

CI: bump scaffolding version

---

.github/workflows/verify-docs.yaml

This PR adds a new gh action to validate the generation of API docs on every PR. 
Related to https://github.com/sigstore/policy-controller/issues/394
Add a github action to verify the API docs generation.

add gh actions to verify docs

---

.github/workflows/kind-cluster-image-policy.yaml
config/300-clusterimagepolicy.yaml
docs/api-types/index.md
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
pkg/client/clientset/versioned/scheme/register.go
pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
pkg/webhook/validator.go
pkg/webhook/validator_result.go
test/e2e_test_cluster_image_policy_with_include_spec.sh
test/testdata/policy-controller/e2e/cip-include-spec-fails.yaml
test/testdata/policy-controller/e2e/cip-include-spec.yaml

Second part of #385 , add includeSpec bool to Policy which will then attach the Spec of the resource to PolicyResult, which
then makes it available for CIP level policy evaluation.
* Add includeSpec bool to spec.Policy which will then make resource Spec available for CIP level policy evaluation.

Attach highest level resource spec to PolicyResult if so desired.

---

.github/workflows/kind-cluster-image-policy-resync-period.yaml
cmd/policy_webhook/main.go
config/policy-webhook.yaml
pkg/reconciler/clusterimagepolicy/controller.go
pkg/reconciler/clusterimagepolicy/controller_test.go
test/kustomize-invalid-policy-resync-period/kustomization.yaml
test/kustomize-policy-resync-period/kustomization.yaml

* Adds policy resync period
* Closes #48 
* Added --policy-resync-period arg policy-webhook for policy resync (default: 10h)
https://github.com/sigstore/docs/pull/40

feat: configurable ClusterImagePolicy resync period

---

cmd/tester/main.go
pkg/webhook/validator.go

:gift: This adds an optional `-resource` flag to `policy-tester` which let's you pass in a resource spec to use for testing `includeObjectMeta` and `includeSpec` policies.
/kind feature
The `policy-tester` now supports `-resource` for validating `includeSpec` and `includeObjectMeta` policies, and the respective functions are public for callers of `ValidatePolicy`.

Feature: Add `-resource` to `policy-tester`

---

.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/policy-tester-examples.yml
cmd/tester/main.go
config/300-clusterimagepolicy.yaml
docs/api-types/index.md
examples/policies/allow-only-pods.yaml
hack/update-codegen.sh
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
pkg/webhook/validator.go
pkg/webhook/validator_result.go
test/e2e_test_cluster_image_policy_with_include_typemeta.sh
test/testdata/policy-controller/e2e/cip-include-typemeta.yaml
test/testdata/resources/job.yaml
test/testdata/resources/pod.yaml

Add includeMetaData (just like includeObjectMeta) that includes TypeMeta (kind, apiVersion) in the PolicyResult
Also fix hack/update-codegen.sh to produce updates to both v1alpha1 and v1beta1. So, while the diffs there look large, it's because it was so out of date.
* Add includeMetaData (just like includeObjectMeta) that includes TypeMeta (kind, apiVersion) in the PolicyResult

Add includeTypeMeta that includes TypeMeta (just like includeObjectMeta)

---

pkg/webhook/validator.go
test/cmd/getoidctoken/main.go

Fix lint issues surfaced by #424

Fix some lint issues surfaced by #424

---

test/cmd/getoidctoken/main.go

to fix the issue found in https://github.com/sigstore/policy-controller/pull/427

fix ioutil deprecation

---

.github/workflows/release.yaml
.github/workflows/tests.yaml

Just redoing #427 on top of the head to see if we can get a release out.

release-script: bump golang to 1.19 (rebased version of #427)

---

.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy.yaml

Bump the tests to use scaffolding release v0.5.4.

update scaffolding releases to v0.5.4

---

.github/workflows/release.yaml
.goreleaser.yaml
release/ldflags.sh
release/release.mk

Generate slsa provenance to our release pipeline.
related to #446

Generate slsa provenance

---

.github/workflows/kind-cluster-image-policy-tsa.yaml

closes https://github.com/sigstore/policy-controller/issues/478

user sigstore cosign-installer

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/kind-e2e-trustroot-crd.yaml
.github/workflows/policy-tester-examples.yml
.github/workflows/release.yaml
release/ko-sign-release-images.sh
test/e2e_test_cluster_image_policy.sh
test/e2e_test_cluster_image_policy_no_tuf.sh
test/e2e_test_cluster_image_policy_with_attestations.sh
test/e2e_test_cluster_image_policy_with_attestations_rego.sh
test/e2e_test_cluster_image_policy_with_source.sh
test/e2e_test_cluster_image_policy_with_trustroot_bring_own_keys.sh
test/e2e_test_cluster_image_policy_with_trustroot_remote.sh
test/e2e_test_cluster_image_policy_with_trustroot_repository.sh
test/e2e_test_cluster_image_policy_with_warn.sh
test/e2e_test_cluster_with_scalable.sh

Signed-off-by: Kenny Leung <kleung@chainguard.dev>
switch to using cosign v2.0.0-rc.0
update use of `--force` to `--yes` for cosign sign|attest, https://github.com/sigstore/cosign/pull/2399
update use of `--no-tlog-upload` to `--tlog-upload=false`, https://github.com/sigstore/cosign/pull/2397

cleanup: switch to using cosign v2.0.0-rc.0

---

examples/README.md
examples/policies/signed-by-gcp-kms-key.yaml

Signed-off-by: Mathieu Benoit <mabenoit@google.com>
Adding a policy example with GCP KMS with associated requirements in terms of GSA's roles and GKE's scope in order to have `policy-controller` working successfully.

Add a policy example for GCP KMS

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy-tsa.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/policy-tester-examples.yml
examples/README.md
test/e2e_test_cluster_image_policy.sh
test/e2e_test_cluster_image_policy_with_attestations.sh
test/e2e_test_cluster_image_policy_with_attestations_rego.sh
test/e2e_test_cluster_image_policy_with_source.sh
test/e2e_test_cluster_image_policy_with_trustroot_bring_own_keys.sh
test/e2e_test_cluster_image_policy_with_trustroot_remote.sh
test/e2e_test_cluster_image_policy_with_trustroot_repository.sh
test/e2e_test_cluster_image_policy_with_tsa.sh
test/e2e_test_cluster_image_policy_with_warn.sh
test/e2e_test_cluster_with_scalable.sh

Remove COSIGN_EXPERIMENTAL env variables from our scripts and docs.

remove COSIGN_EXPERIMENTAL evn var

---

.github/workflows/release.yaml
.goreleaser.yaml

- set yes confirmation flag and bump timeout

set yes confirmation flag and bump timeout

---

test/testdata/policy-controller/tester/cip-public-keyless.yaml

It misses the identities so it fails when used with the policy-tester.

fix: cip keyless tester

---

README.md

Add some missing documentation on how to verify an image against a TSA server.

docs: verify an image against a TSA

---

pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
test/testdata/policy-controller/invalid/keylessref-with-multiple-properties.yaml
test/testdata/policy-controller/invalid/v1beta1-invalid-hash-algo.yaml
test/testdata/policy-controller/invalid/v1beta1-keylessref-with-multiple-properties.yaml
test/testdata/policy-controller/valid/v1beta1-valid-policy-glob.yaml
test/testdata/policy-controller/valid/v1beta1-valid-policy.yaml
test/testdata/policy-controller/valid/valid-keyless-with-source.yaml
test/testdata/policy-controller/valid/valid-policy-glob.yaml
test/testdata/policy-controller/valid/valid-policy-hash-algo.yaml
test/testdata/policy-controller/valid/valid-policy-keyless-ignore-sct.yaml
test/testdata/policy-controller/valid/valid-policy-match-resource-label.yaml
test/testdata/policy-controller/valid/valid-policy-match-resource.yaml
test/testdata/policy-controller/valid/valid-policy.yaml

Throw an error whenever the secretRef sets a namespace that isn't equal to the namespace where policy-controller was deployed.
Add validation for the secretRef.namespace field.

add validation for secretRef.namespace value

---

.ko.yaml

Use cgr.dev registry again

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy-tsa.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/kind-e2e-trustroot-crd.yaml
.github/workflows/release.yaml
go.mod
go.sum
pkg/webhook/validator.go

bump cosign to v2.0.0 release

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy-tsa.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/kind-e2e-trustroot-crd.yaml
.github/workflows/policy-tester-examples.yml
.github/workflows/release.yaml

Stop setting the cosign version in our gh actions, and use the default cosign version from the installer.

Use default cosign-installer version

---

.github/workflows/scorecard_action.yml

Bumping scorecard github actions to use latest version.

bump scorecard script to use latest versions

---

README.md

Adding the badges and the Logo to the README.

Add logo and badges

---

.github/workflows/tests.yaml
.golangci.yml
Makefile
cmd/policy_webhook/main.go
cmd/webhook/main.go
pkg/apis/config/sigstore_keys.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_defaults.go
pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
pkg/apis/policy/v1alpha1/trustroot_defaults.go
pkg/apis/policy/v1alpha1/trustroot_validation.go
pkg/apis/policy/v1beta1/clusterimagepolicy_conversion.go
pkg/apis/policy/v1beta1/clusterimagepolicy_conversion_test.go
pkg/apis/policy/v1beta1/clusterimagepolicy_defaults.go
pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
pkg/policy/parse.go
pkg/policy/verifier.go
pkg/reconciler/clusterimagepolicy/controller.go
pkg/reconciler/clusterimagepolicy/resources/configmap.go
pkg/reconciler/testing/v1alpha1/factory.go
pkg/reconciler/trustroot/controller.go
pkg/reconciler/trustroot/resources/configmap.go
pkg/tuf/repo.go
pkg/tuf/repo_test.go
pkg/webhook/nocache.go
pkg/webhook/validator.go

- fix build using ko-local
- update golangci-lint to v1.53.x
- fix lints

general Updates

---

pkg/webhook/validator.go

make the log entry for when a policy validation failed more useful.
adding additional information on the actual error/warn for easier debugging.
Logged error when policy validation failed.

logging: add more details when validation failed

---

.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy-tsa.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/kind-e2e-trustroot-crd.yaml
test/e2e_test_cluster_image_policy_with_trustroot_repository.sh

Let's bump the usage scaffolding version!

bump scaffolding version

---

.github/workflows/build.yaml
.github/workflows/kind-cluster-image-policy-no-tuf.yaml
.github/workflows/kind-cluster-image-policy-resync-period.yaml
.github/workflows/kind-cluster-image-policy-trustroot.yaml
.github/workflows/kind-cluster-image-policy-tsa.yaml
.github/workflows/kind-cluster-image-policy.yaml
.github/workflows/kind-e2e-cosigned.yaml
.github/workflows/kind-e2e-trustroot-crd.yaml

The `setup-ko` action has been moved to the `ko-build` GitHub org, so this PR updates all references to the original location.

Update setup-ko action reference

---

pkg/apis/policy/common/validation.go

Support for ARN in AWS China uses arn:aws-cn:kms:[region]:[account_id]:key/[kms_id].
The following are the supported partitions:
aws - AWS Regions
aws-cn - China Regions
aws-us-gov - AWS GovCloud (US) Region
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html

Added kms support for AWS China region

---

.github/workflows/build.yaml

push incremental builds to GHCR instead of gcr

---

.github/workflows/build.yaml

- fix post submit job
see: https://github.com/sigstore/policy-controller/actions/runs/12433003788/job/34713622190

fix post submit job

---

.github/dependabot.yml

Update Dependabot config to use weekly grouped updates

---

.github/workflows/lint.yaml
.github/workflows/tests.yaml
.golangci.yml
pkg/reconciler/testing/v1alpha1/clusterimagepolicy.go
pkg/reconciler/testing/v1alpha1/trustroot.go
pkg/webhook/validator.go

This updates to version 2 of the golangci-lint config file format.
This was generated with the golangci-lint migrate command.
There are a few fixes I made to the Go source to fix some linter errors.

Update golangci-lint config to version 2

---

pkg/webhook/validator.go
pkg/webhook/validator_test.go

When the authority specifies using NewBundleFormat and a RFC3161Timestamp, transparency log should be ignored. 
closes https://github.com/sigstore/policy-controller/issues/1873
[Fix] properly ignore transparency log during validation when using NewBundleFormat and RFC3161Timestamp

ignore tlog when using RFC3161Timestamp
