- .ko.yaml
- go.mod
- go.sum
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/auth.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/client.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/kv.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/kv_v1.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/kv_v2.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/lifetime_watcher.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/logical.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/output_policy.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/output_string.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/plugin_helpers.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/secret.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_hastatus.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_mfa.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_monitor.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_plugins.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_raft.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/api/sys_seal.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/sdk/helper/certutil/helpers.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/sdk/helper/certutil/types.go
- third_party/VENDOR-LICENSE/github.com/hashicorp/vault/sdk/version/version_base.go
Signed-off-by: Jason Hall <jason@chainguard.dev>
This change bumps some vulnerable deps reported in https://github.com/sigstore/policy-controller/issues/26
```
go get -u github.com/hashicorp/vault/api@latest
go get -u github.com/hashicorp/vault/sdk@latest
go get -u google.golang.org/protobuf@latest (no change)
```
It also removes the `defaultBaseImage` in .ko.yaml, which made the controller images based on `gcr.io/distroless/base:debug-nonroot`, I think unnecessarily. I think this was selected as the base image for `cosign` and just picked up as the default when the K8s components were added to the repo.
In any case, I think it's safe to remove them now.
After this change, there are still some detected vulnerabilities:
```
$ grype $(ko build ./cmd/policy_webhook/)
NAME …
```
> Bump some vulnerable dependencies; base on distroless/static

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
Please see the following PRs in cosign where these new types are added:
- https://github.com/sigstore/cosign/pull/1974
- https://github.com/sigstore/cosign/pull/1977
> Add spdxjson and cyclonedx as supported predicate types

- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
- test/e2e_test_cluster_image_policy.sh
- test/e2e_test_cluster_image_policy_with_attestations.sh
- test/testdata/policy-controller/e2e/cip-key-and-keyless.yaml
- test/testdata/policy-controller/e2e/cip-key-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-attestations.yaml
Fix #28 by treating multiple authorities as OR instead of AND. This was what it was supposed to be as per the spec all along.
Fixes
```release-note
* Fix bug #28 where multiple authorities were treated as AND instead of OR as specified.
```
> Fix #28. Treat multiple authorities as OR instead of AND.

- pkg/apis/glob/glob.go
- pkg/apis/glob/glob_test.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
In #60, support for exact strings of image refs with a digest stopped working.
Example:
```
ghcr.io/foo@sha256:5504f2a95018e3d8a52d80d9e1a128c6ea337581808ff9fe96f5628ce2336350
```
This just adds the `@` character in the regex pattern for glob string validation.
> Allow for @ symbol on globs to support image refs with digest

- .github/workflows/policy-tester.yml
- .gitignore
- Makefile
- README.md
- cmd/tester/main.go
- test/testdata/policy-controller/tester/cip-public-keyless.yaml
Adding a simple tool for validating ClusterImagePolicy resources against various images on the command line
> Add policy-tester CLI for testing ClusterImagePolicies

- .github/workflows/kind-cluster-image-policy-with-attestations.yaml
- .github/workflows/kind-cluster-image-policy.yaml
- .github/workflows/kind-e2e-cosigned.yaml
- remove v1.21 k8s which is deprecated and add v1.24
- update scafolding to use release v0.3.0
- update knative to use v1.5.0 release
`NONE`
`NONE`
> Update k8s clusters test

- test/e2e_test_cluster_image_policy.sh
- test/e2e_test_cluster_image_policy_with_attestations.sh
I was seeing a race running e2e tests where immediately after applying a policy we immediately expect it to be enforced, but it takes time to compile and distribute the policy configmap.
As I was copying this other places, I noticed that the sleeps already existed, so I added my more detailed comment to the instances I found.
cc @vaikas @hectorj2f
> Avoid test race condition.

- pkg/webhook/validator.go
Refactor the ValidatePolicy that includes the CIP level policy validation. This makes for example, cmd/tester validate the entire CIP.
> Refactor entire policy validation into ValidatePolicy.

- cmd/tester/main.go
@jdolitsky found in #108 that the tester was not handling the Keyful validation correctly. This was caused by us not 'round-tripping' the webhook cip, which in the Policy-Controller path is marshalled by the reconciler and unmarshalled before handing to the validator path. One thing the unmarshaller does is convert the inlined data blocks into crypto keys which is what the policy-controller validator uses.
So, this PR adds that round tripping before using the webhook cip.
* Fix bug in tester which was not handling keyful signatures / attestations correctly.
> Fix keyful handling in tester.

- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- pkg/webhook/validator_test.go
This follows up my previous PR that started to access the Issuer/Subject metadata to also include all of the current cert extensions.
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
```release-note
Start to incorporate the cert extensions into the PolicySignature.
```
cc @vaikas @jdolitsky @hectorj2f
> Add all of the current extensions.

- test/e2e_test_cluster_image_policy_with_attestations.sh
Exit policy validation test early due to #130 so that we can cut a release and have a working head. The test is broken, we have validated this several ways and have a repro, just lacking cue expertise to make this go atm.
> Remove test due to #130

- .github/workflows/codeql-analysis.yml
> fix codeql job

- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- pkg/webhook/validator_test.go
This change factors a new `PolicyAttestation` type so that we can encode additional information for attestations beyond just signature fields.
This change adds the predicate type (which would otherwise require parsing the CIP to know), and the payload (included for callers of ValidatePolicy, so they don't have to refetch the `oci.Signature`'s `Payload()`).
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
The policy results for attestations now includes the predicate type (available to CIP policies) and the attestation payload (not available to CIP policies since we've already run the policy over them).  To achieve this, there is a potentially breaking change to the signature of `ValidatePolicy` to wrap the attestation's `PolicySignature` in a new `PolicyAttestation` type, however, to …
> Include the predicate type and payload for attestations.

- .github/workflows/policy-tester-examples.yml
- .gitignore
- examples/README.md
- examples/policies/signed-by-aws-kms-key.yaml
- examples/policies/signed-by-github-actions.yaml
Adds a Github actions and AWS KMS example to the example policies directory. This expands the current examples beyond SBOM stuff and shows some common signing patterns
NONE
Will possibly send these over to the sigstore docs if desired.
> Add two more example policies

- .github/workflows/kind-cluster-image-policy-scaling.yaml
- .github/workflows/kind-cluster-image-policy-with-attestations.yaml
- .github/workflows/kind-cluster-image-policy.yaml
> Use scaffolding v0.4.2 for tests.

- config/200-clusterrole.yaml
This PR gets the development ClusterRole in sync with the Helm Charts: https://github.com/sigstore/helm-charts/blob/main/charts/policy-controller/templates/policy-webhook/clusterrole_policy_webhook.yaml. This also adds support for OpenShift.
Closes #145 
Signed-off-by: Andrés Torres <andrest@vmware.com>
* Added finalizers permissions to ClusterRole in development.
No docs change are required. The improvement is mainly targeted for developers and maintainers.
> Add finalizers permissions to ClusterRole

- .github/workflows/kind-cluster-image-policy.yaml
- config/webhook.yaml
- test/e2e_test_cluster_image_policy.sh
- test/e2e_test_cluster_image_policy_with_attestations.sh
- test/e2e_test_cluster_with_scalable.sh
- test/kustomize/kustomization.yaml
* Policy Controller now uses TUF root that gets initialized in an init container.
> Add cosign initialize as an init container to initialize TUF.

- test/e2e_test_cluster_image_policy.sh
- test/e2e_test_cluster_image_policy_with_attestations.sh
- test/e2e_test_cluster_image_policy_with_warn.sh
- test/e2e_test_policy_crd.sh
- test/testdata/policy-controller/warn/missing-identity.yaml
- test/testdata/policy-controller/warn/missing-issuer.yaml
- test/testdata/policy-controller/warn/missing-subject.yaml
- test/testdata/policy-controller/warn/v1beta1-missing-identity.yaml
- test/testdata/policy-controller/warn/v1beta1-missing-issuer.yaml
- test/testdata/policy-controller/warn/v1beta1-missing-subject.yaml
Add tests for making sure that when we create CIPs that warnings are produced and they match what we expect.
> Add warn tests for creating CIP with missing identities.

- cmd/tester/main.go
As seen on #195 the tester would exit on `warning` level validation errors. So, split out the warnings and print them
separately and do not exit on them.
> Do not exit on warnings on CIP.

- examples/policies/keyless-attestation-sbom-spdxjson.yaml
- update CIP to fix tests when running in the push to main and in keyless mode
```
main.go:93: Using the following cip:
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
creationTimestamp: null
name: keyless-attestation-sbom-spdxjson
spec:
authorities:
- attestations:
- name: must-have-spdxjson
policy:
data: |
predicateType: "https://spdx.dev/Document"
type: cue
predicateType: spdxjson
keyless:
url: https://fulcio.sigstore.dev/
name: keyless
images:
- glob: '**'
mode: enforce
main.go:97: CIP is invalid: missing field(s): spec.authorities[0].keyless.identities
Error: Process completed with exit code 1.
```
see https://github.com/sigstore/policy-controller/runs/8058669693?check_suite_focus=true
> update CIP to fix tests when running in the push to main and in keyless mode

- go.mod
- go.sum
- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
Extract the namespace from the `AdmissionRequest` if the resource doesn't have the namespace field set correctly. Fixes #143.
* Fixes #143. Webhook was incorrectly rejecting pods deployed in a non-default namespace when `imagePullSecrets` were involved.
> Fix webhook looking for credentials in the wrong namespace

- pkg/apis/config/image_policies_test.go
- pkg/apis/config/testdata/config-image-policies.yaml
- pkg/apis/config/testdata/config-invalid-image-policy.yaml
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
* Add explicit check for invalid keys. This should not happen, but.
* Add explicit check to make sure there's a publickey, again ☝️ 
* Fail if config file is incorrect.
* Add an explicit check and fail if config does not contain valid inline data. This should not happen because the keys get validated before serializing them into the configmap.
* Add an explicit check for when a KeyRef does not contain a valid PublicKey. Prior to this it would have been mistakenly flagged as not having a KeyRef, Static of KeylessRef.
> Add explicit check for invalid keys. This should not happen, but.

- pkg/reconciler/clusterimagepolicy/clusterimagepolicy.go
- test/e2e_test_cluster_image_policy.sh
- test/testdata/policy-controller/e2e/cip-key-secret.yaml
Add e2e test using key.secretRef.
> Add e2e test with secretRef.

- test/testdata/policy-controller/e2e/cip-key-and-keyless.yaml
- test/testdata/policy-controller/e2e/cip-key-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-key.yaml
- test/testdata/policy-controller/e2e/cip-keyless-warn.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-identities-mismatch.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-identities.yaml
- test/testdata/policy-controller/e2e/cip-keyless.yaml
- test/testdata/policy-controller/e2e/cip-requires-two-signatures-and-two-attestations.yaml
- test/testdata/policy-controller/e2e/cip-static-fail.yaml
- test/testdata/policy-controller/e2e/cip-static-pass.yaml
When doing e2e tests against existing clusters like gke, I find it easier to use different registries. So relax the glob so they just work.
> Relax glob so easier to run e2e tests against other clusters.

- cmd/webhook/main.go
- config/webhook.yaml
The intention is to remove a flag that has been added with our first alpha version but it does not fit anymore in our declarative way of defining policies and authorities. 
Following the Kubernetes deprecation policy for flags and beta versions, we will remove this flag in one release.
Add a deprecation message to remove the -secret-name flag in the future.
> Start deprecation of --secret-name

- release/ko-sign-release-images.sh
> remove not needed env vars

- release/ko-sign-release-images.sh
- `ko` now output more digests (before 0.11.2 release the output was just one) and that was passing as a unique big string to cosign failing the job
> remove double quotes, looks like it is passing as a single string to cosign and not as an array

- cmd/tester/main.go
- cmd/webhook/main.go
- examples/policies/release-signed-by-github-actions.yaml
Sometimes it's handy to not fetch the CIP from the file, but for example by hosting the CIP for example on a website.
So, treat the -policy so that if it starts with https:// or http:// it will fetch it.
Example invocation:
```
./tester -policy="https://raw.githubusercontent.com/sigstore/policy-controller/main/examples/policies/signed-by-github-actions.yaml" -image=gcr.io/projectsigstore/policy-webhook@sha256:d1e7af59381793687db4673277005276eb73a06cf555503138dd18eaa1ca47d6
```
Which fails with the expected, issuer does not match because tester uses main, but the released Subject is:
```
https://github.com/sigstore/policy-controller/.github/workflows/release.yaml@refs/tags/v0.3.0
```
> Allow fetching CIPs from URLs.

- .goreleaser.yaml
- cmd/tester/main.go
- release/release.mk
- add version flag
- add tester binary to the release process
Fixes: https://github.com/sigstore/policy-controller/issues/232
> add tester binary to the release process

- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
:bug: This plumbs context through to GGCR in all of the places we pass through the keychain.
This is necessary for registry interactions to show up in distributed traces.
/kind bug
```release-notes
Registry interactions should now show up in distributed traces.
```
N/A
> Fix: Plumb context through to GGCR.

- config/config-policy-controller.yaml
- test/e2e_test_cluster_image_policy.sh
- test/e2e_test_cluster_image_policy_with_warn.sh
- test/e2e_test_policy_controller.sh
fixed #235 
* Any image not matching a policy is 'deny' by default.
> deny by default.

- config/config-policy-controller.yaml
As per the comments, this is taking out the redundant `deny` from the configmap which might make upgraders harder, as
per:
https://github.com/sigstore/policy-controller/pull/279#discussion_r984646624
@mattmoor
> Since by default we deny all, just drop it from CM.

- cmd/policy_webhook/main.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/config/store.go
- pkg/config/store_test.go
- pkg/config/testdata/allow-empty-authorities.yaml
- pkg/webhook/validator_test.go
This PR aims to expose a new configuration setting to allow creating CIP without authorities, as explained in https://github.com/sigstore/policy-controller/issues/275.
related to: https://github.com/sigstore/policy-controller/issues/275
> Add a configuration field to allow CIP with no authorities

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
:bug: The addition of the new config to v1beta1 without `OrDefaults` is breaking (segfault!) to downstream callers of `Validate()`, so this changes things to use `OrDefaults` for when that configuration is unavailable.
:bug: I also noticed that the v1alpha1 validation wasn't checking the config, so depending on the version we validate with this is breaking, which creates some weird semantics with conversion.
This makes things use `OrDefaults` and copies the logic to `v1alpha1`.
/kind bug
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
> Fix: Check flag in v1alpha1, use OrDefaults to avoid breaking change.

- .github/workflows/codeql-analysis.yml
CodeQL runs take a lot of time whenever we open PRs. We decided to run it on post-merge basis for now.
Run codeql analysis on post-merge basis
> run codeql on post-merge

- cmd/webhook/main.go
- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
:bug: I was debugging an issue in a downstream call to `ValidatePolicy` where I noticed that we already expect `SourceSignaturePullSecretsOpts` to fetch the kubernetes client off of `ctx` via `kubeclient.Get(ctx)`.
Given that this is a fairly uncommon code path to exercise, I wanted to make the way we access the client more consistent so that downstream callers discover this issue more quickly and can fix the problem before it hits in the corner case they likely have not tested.
/kind bug
Fixes a crash during the validation webhook when image pull secrets are used.
> Fix: Always use `kubeclient.Get()` for fetching k8s client.

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
Add a validation to avoid setting wrong values for the source.OCI.
Add a validation  to avoid setting wrong values for the source.OCI.
> Add validation for the oci repository field

- config/policy-webhook.yaml
- config/webhook.yaml
:bug: TIL that `all` isn't recognized by K8s upstream, and they hardcode an `ALL` constant
ref: https://github.com/knative-sandbox/eventing-rabbitmq/pull/954#pullrequestreview-1153348371
/kind bug
Change the way we drop capabilities from `all` to `ALL`, which is the constant K8s expects.
cc @hectorj2f @vaikas
> Fix: switch from `all` to `ALL` when dropping capabilities.

- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- pkg/webhook/validator_test.go
:gift: This incorporates an identifier for signatures and attestations into a Policy Result, which should be suitable for identifying a signature or attestation across policy invocations (possibly across multiple policies).
/kind feature
`PolicyResult` now includes an `Id` in `Policy{Signature,Attestation}` suitable for identifying the signature or attestation across contexts.
> Feature: Incorporate an identifier for signatures and attestations.

- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- test/e2e_test_policy_crd.sh
- test/testdata/policy-controller/empty-authorities/authorities-absent.yaml
- test/testdata/policy-controller/empty-authorities/authorities-present.yaml
Closes #361 
Add `omitempty` to `authorities` to allow the `spec.authorities` field to not be specified.
This field being present and not nil is already conditionally validated (with the validation happening by default), so this should be safe to add.
To test the change:
1. Ensure `policy-controller` configuration includes `fail-on-empty-authorities: "false"`
2. Apply the following YAML:
```
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
name: empty-authorities
spec:
images:
- glob: 'index.docker.io/*'
EOF
```
This should work, fails on latest main, but works with the code change from this PR.
Allow `spec.authorities` field to not be specified
N/A
> fix: allow spec.authorities field to not be specified

- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
- test/testdata/policy-controller/e2e/cip-requires-two-signatures-and-two-attestations.yaml
While debugging a cue policy validation, I found that the spec.policy field was not been converted, and so no validation was done based on the cue data.
Fix: Policy converter was ignore spec.policy fields when converting v1beta1 policies.
> fix: v1beta1 version converter that ignored the field spec.policy

- .github/workflows/kind-cluster-image-policy.yaml
- cmd/tester/main.go
- config/300-clusterimagepolicy.yaml
- docs/api-types/index.md
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- pkg/webhook/validator_test.go
- test/e2e_test_cluster_image_policy_with_config_file.sh
- test/e2e_test_cluster_image_policy_with_fetch_config_file.sh
- test/testdata/policy-controller/e2e/cip-config-file-policy-fails.yaml
- test/testdata/policy-controller/e2e/cip-config-file-policy.yaml
Addresses the configfile part of #385
Add flag to spec.policy `fetchConfigFile` that when set to true will fetch and make the ConfigFile available for CIP level
policy evalutions.
* Add FetchConfigFile into cip.Spec.Policy that allows one to fetch OCI config files (https://github.com/opencontainers/image-spec/blob/main/config.md) that are then available for evaluation in the cip.Spec.Policy
> Add FetchConfigFile to Policy that allows you to fetch and evaluate policy against container image configfile.

- .github/workflows/kind-cluster-image-policy.yaml
- config/300-clusterimagepolicy.yaml
- docs/api-types/index.md
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- test/e2e_test_cluster_image_policy_with_include_objectmeta.sh
- test/testdata/policy-controller/e2e/cip-include-objectmeta-fails.yaml
- test/testdata/policy-controller/e2e/cip-include-objectmeta.yaml
Continuation of #406 in a way, add includeObjectMeta into spec.policy which when set to true will include the resources ObjectMeta (things like labels/annotations) in the PolicyResult that then in turn are available in evaluating with CIP.Policy iff at least one authority matches.
* Continuation of #406 in a way, add includeObjectMeta into spec.policy which when set to true will include the resources ObjectMeta (things like labels/annotations) in the PolicyResult that then in turn are available in evaluating with CIP.Policy iff at least one authority matches.
> Add includeObjectMetadata for including objectMeta in CIP policy eval.

- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- test/e2e_test_cluster_image_policy_with_include_objectmeta.sh
- test/testdata/policy-controller/e2e/cip-include-objectmeta-fails.yaml
- test/testdata/policy-controller/e2e/cip-include-objectmeta.yaml
:broom: This renamed `objectMeta:` to `metadata:` in `PolicyResult` so that the shape of what folks write for validation aligns with the shape of Kubernetes resources.
/kind cleanup
🚨  THIS IS A BREAKING CHANGE 🚨, but talking to @vaikas we wanted to rip off the band-aid now before the field has meaningful adoption and cut a 0.5.1.
With this, folks can now write policies with the shape:
```yaml
metadata:
annotations:
foo: "bar"
spec:
containers:
- name: "baz"
```
> Cleanup: Rename `objectMeta` to `metadata` to align with K8s shape.

- .github/workflows/kind-cluster-image-policy-no-tuf.yaml
- keep the matrix jobs running if one fail
similar we have for other jobs
> keep the matrix jobs running if one fail

- pkg/webhook/validator.go
This PR exposes the webhook validator Getters for downstream consumers:
- `GetIncludeTypeMeta`
- `GetIncludeObjectMeta`
- `GetIncludeSpec`
> expose webhook validator getters

- cmd/tester/main.go
closes: https://github.com/sigstore/policy-controller/pull/453
Use UnmarshalStrict to avoid any fields that are found in the data that do not have corresponding struct members, or mapping keys that are duplicates, will result in an error.
policy-tester: use UnmarshalStrict.
> policy-tester: use UnmarshalStrict

- .github/workflows/kind-cluster-image-policy.yaml
- config/300-clusterimagepolicy.yaml
- docs/api-types/index-v1alpha1.md
- docs/api-types/index.md
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/reconciler/clusterimagepolicy/clusterimagepolicy.go
- pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
- pkg/reconciler/clusterimagepolicy/controller.go
- pkg/reconciler/testing/v1alpha1/clusterimagepolicy.go
- pkg/reconciler/testing/v1alpha1/factory.go
- test/e2e_test_cluster_image_policy_from_configmap_with_fetch_config_file.sh
- test/testdata/policies/cue-policy-config.cue
- test/testdata/policy-controller/e2e/cip-config-file-policy-from-configmap.yaml
* Implement configMapRef in both attestations and CIP level policies. Addresses #454 
* Makes it easier to edit policies so that you don't have to muck with them in the middle of yaml happiness.
* Implement configMapRef in both attestations and CIP level policies. Addresses #454
> Add support for policy.configMapRef in attestation / cip.spec

- pkg/webhook/validator.go
- test/e2e_test_cluster_image_policy_with_repository.sh
* If a trustroot is specified, and has keys but does not have URL there use the one from the TLog.URL entry. Also add a test for validating that an entry has been uploaded to Rekor.
> If TLog.url is specified, use it if trustroot does not have one + test.

- pkg/webhook/validator.go
:bug: This fixes two problems fetching config files for a private multi-arch image:
1. We weren't properly surfacing errors fetching the config files.
2. We weren't passing the `remote.Option` list to the recursive call (so the `remote.WithKeychain` is dropped!)
With these changes downstream, I was able to successfully verify a private multi-arch image index.
/kind bug
Fixes: https://github.com/sigstore/policy-controller/issues/460
This fixes `fetchConfigFile` for private multi-arch images, and fixes the error message handling along the same path.
N/A
cc @hectorj2f @vaikas
> Fix: Fix private multi-arch `fetchConfigFile`

- pkg/apis/policy/v1alpha1/trustroot_validation.go
We had a wrong reference to the `subject` api field when it should be to `certChain`.
> fix: wrong api field ref in error msg

- pkg/apis/policy/v1alpha1/trustroot_validation.go
We could create a TrustRoot with a list of TSAs servers without defining any additional CA.
> chore: Relax certificate authority validation in trustRoots

- pkg/apis/config/sigstore_keys.go
- pkg/apis/policy/v1alpha1/trustroot_validation.go
- pkg/apis/policy/v1alpha1/trustroot_validation_test.go
Add missing validation for the certificate chain, in particular for the timestamp authorities.
> chore: add TSA cert chain validation

- .github/workflows/kind-cluster-image-policy-trustroot.yaml
Fix the following issue in the github actions:
closes: https://github.com/sigstore/policy-controller/issues/475
> fix: script field identation

- pkg/apis/config/image_policies.go
- pkg/apis/config/image_policies_test.go
- pkg/apis/config/testdata/config-image-policies.yaml
:bug: I noticed that the resource matching logic was keying exclusively off of `kind` to map to a GVR, and not validating the `apiVersion` which could lead to false positive matches if other types were added to the webhook's resource match.
For example, the code today would match:
```yaml
apiVersion: mattmoor.dev/v1
kind: Deployment
```
However, the new logic does not!  I also tweaked the loop a bit to try and reduce the complexity of the boolean expressions and reduce indentation for readability.
/kind bug
Signed-off-by: Matt Moore <mattmoor@chainguard.dev>
Fixes a bug where `ClusterImagePolicy`'s `match` might apply to resources with mismatched `apiVersion` if those types are let through the webhook.
N/A
> Fix: Use the `apiVersion` when matching resources.

- cmd/tester/main.go
- pkg/policy/README.md
- pkg/policy/parse.go
- pkg/policy/parse_test.go
- pkg/policy/policy.go
- pkg/policy/policy_test.go
- pkg/policy/validate.go
- pkg/policy/validate_test.go
- pkg/policy/verifier.go
- pkg/policy/verifier_test.go
:gift: This change factors a new small library `./pkg/policy` which is intended to streamline incorporating CIP validation into downstream tooling.
For a (much) more verbose explanation see [here](https://github.com/ko-build/ko/issues/356#issuecomment-1368273840), but the general idea behind this is to allow CIP's to gate consumption of images in other contexts, for example the base images in build tools such as `ko` or `kaniko`.  The idea is to enable the tool providers to bake-in default policies for default base images, and optionally expose configuration to let users write policies to authorize base images prior to consumption.
For example, I might write the following `.ko.yaml`:
```yaml
verification:
noMatchPolicy: deny
policies:
- data: |
- url: …
```
> Feature: Create an interface for downstream CIP integrations.

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
Allow Fully specified URLs in the predicate type in addition to 'convenience' ones. 
Got bit by the cyclonedx changing here, which then percolated to cosign, so now you can't validate something that has a type=cyclonedx if the attestation was created with a different version of cosign.
https://github.com/in-toto/in-toto-golang/commit/86e515c6e15f0d9bc2cc9cb8253165f8176f6ce6
🎁 Allow fully specified URLs as PredicateTypes.
> Allow fully specified URLs in predicateTypes.

- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
- test/testdata/policy-controller/e2e/cip-key-and-keyless.yaml
Whenever you define CIP a keyless authority without a ctlog or a trustRoot, the controller will assume you are verifying your images using the sigstore ctlog `rekor.sigstore.dev`. This PR supports the old legacy behavior of keyless verification while supporting TrustRoot references. 
```
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
name: policy
spec:
images:
- glob: "**" # Your image here
authorities:
- name: keyatt
keyless:
url: "https://fulcio.sigstore.dev"
identities:
- issuerRegExp: ".*"
subjectRegExp: ".*"
```
The controller fetches the RekorPublic keys while keeping the RekorClient nil which defaults to an offline behavior.
closes https://github.com/sigstore/policy-controller/issues/479
> Fix keyless behauvior when ctlog is absent

- test/testdata/policy-controller/invalid/v1beta1-empty-keyref-and-keylessref.yaml
This PR changes the expected error message when having a CIP with empty key/keyless fields.
> test: change error message for empty keyless/key

- config/300-clusterimagepolicy.yaml
- docs/api-types/index-v1alpha1.md
- docs/api-types/index.md
- pkg/apis/config/image_policies_test.go
- pkg/apis/config/testdata/config-image-policies.yaml
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- test/e2e_test_cluster_image_policy.sh
- test/testdata/policy-controller/e2e/cip-key-and-keyless-ignore-sct.yaml
- test/testdata/policy-controller/valid/valid-policy-keyless-ignore-sct.yaml
`InsecureIgnoreSCT` flag in cosign cli was not supported in the policy-controller. There wasn't a way to specific this type of behavior for the keyless authorities. Therefore, we decided to add a new API field to handle SCT.
closes to: https://github.com/sigstore/policy-controller/issues/505
> Add InsecureIgnoreSCT field to the keyless authorities

- config/200-clusterrole.yaml
- config/300-clusterimagepolicy.yaml
- config/300-trustroot.yaml
Break away from the #533 only the subresource & rbac changes to make updates easier. This way we can roll out the changes more safe in the next release without having to spec out the order of updates. We'll do a fast follow with the code changes.
* Add "status" as a subresource for CIP/Trustroot as well as the RBAC for the updates.
> only sub&rbac.

- .github/workflows/release.yaml
Looks like the releaser is right at the hairy edge, so bump it.
https://github.com/sigstore/policy-controller/actions/runs/4038223564/jobs/6942272664
Looks like it's been hovering there, so just bumping to 60. Previous runs:
https://github.com/sigstore/policy-controller/actions/runs/3670391147/jobs/6204895886
> bump timeout for goreleaser to 60 minutes.

- Makefile
- release/README.md
- fix policy controller yaml filename and update release doc
the release was generating the filename as `policy-controller-dirty-tag.yaml` because the `GIT_TAG` is not set and we use `GIT_VERSION` instead
> fix policy controller yaml filename and update release doc

- .github/workflows/policy-tester-examples.yml
This fixes the following issue in our CI: 
https://github.com/sigstore/policy-controller/actions/runs/4046526388/jobs/6959420147
> add COSIGN_YES env var to gh action

- pkg/reconciler/clusterimagepolicy/clusterimagepolicy.go
- pkg/reconciler/clusterimagepolicy/clusterimagepolicy_test.go
Add UT for fetching policy from URL.
Also simplify the SHA computation inlining it.
> Add UT for fetching URL. Simplify SHA calc.

- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
When testing keyless verifications, I found the ConfigMap was not populating the insecureSCT flag as part of a policy definition.
> fix policy conversion from v1beta1 to v1alpha1

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- test/testdata/policy-controller/invalid/invalid-authority.yaml
- test/testdata/policy-controller/invalid/v1beta1-valid-keyref-and-keylessref.yaml
- test/testdata/policy-controller/invalid/valid-keyref-and-keylessref.yaml
Nowadays, the validation allows setting an authority with only the rfc3161timestamp reference. However, we should not verify a signed image without including the expected key or keyless block. Therefore we add the required validation here.
Closes #556 
Improve validation when specifying an authority with a RFC3161Timestamp block to require keys.
> Improve validation when specifying a rfc3161timestamp

- README.md
I realized this comment was wrong in the README.md
> fix wrong documentation for the signaturePullSecrets field

- config/300-clusterimagepolicy.yaml
- docs/api-types/index-v1alpha1.md
- docs/api-types/index.md
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion_test.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/zz_generated.deepcopy.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- test/e2e_test_cluster_image_policy_with_source.sh
- test/testdata/policy-controller/e2e/cip-keyless-with-source-prefix-tag.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-source.yaml
Fixes #577 
Fixes: #360 
As described in #360, last entry in the list wins, which is surprising and wrong. So, limit Source to only have 1 entry in the list for correctness.
Add source.tagPrefix field that allows one to get verify parity when signing and attesting with: `--attachment-tag-prefix` 
Support tag-prefix for verifying signature / attestation.
**Breaking Change** You can only have 1 source specified for Authority.
> Only allow 1 source. Add tagPrefix field to source.

- cmd/policy_webhook/main.go
- pkg/apis/policy/common/validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
:broom: This change moves a bunch of shared constants from `v1alpha1`/`v1beta1` into `common`
:broom: This also changes the behavior of `ValidResourceNames` slightly.  Rather than having the CIP validation bake in a fixed set of resources in the library (in a private variable), the binary entrypoint defines these close to where we set up the resource map, since these must be consistent!
/kind cleanup
Enable the controller entrypoint to control the supported resource set validated in the webhook.
> Cleanup: Move where we restrict resource types.

- .github/workflows/build.yaml
After merging the latest PRs, I found we had some errors here: https://github.com/sigstore/policy-controller/actions/runs/4245710944/jobs/7381577302
> fix: set COSIGN_YES env var for github action - Build CI

- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_validation_test.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_validation_test.go
- test/testdata/policies/cue-vuln-fails.cue
- test/testdata/policies/cue-vuln-works.cue
- test/testdata/policies/cue-works.cue
- test/testdata/policy-controller/e2e/cip-key-with-attestations-no-rekor.yaml
- test/testdata/policy-controller/e2e/cip-key-with-attestations-rego.yaml
- test/testdata/policy-controller/e2e/cip-key-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-attestations-rego.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-source-prefix-tag.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-trustroot-remote-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-trustroot-repository-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-keyless-with-trustroot-with-attestations.yaml
- test/testdata/policy-controller/e2e/cip-requires-two-signatures-and-two-attestations-rego.yaml
- test/testdata/policy-controller/e2e/cip-requires-two-signatures-and-two-attestations.yaml
- test/testdata/policy-controller/valid/v1beta1-valid-policy.yaml
- test/testdata/policy-controller/valid/valid-policy-hash-algo.yaml
- test/testdata/policy-controller/valid/valid-policy-match-resource-label.yaml
- test/testdata/policy-controller/valid/valid-policy-match-resource.yaml
- test/testdata/policy-controller/valid/valid-policy.yaml
Fixes: #608
Fixes: #609 
Deprecate and start warning on short-names for the predicateTypes.
Also warn for non RFC3986 predicateTypes.
Deprecate and start warning on short-names for the predicateTypes (things like 'vuln', 'custom')
Warn for non RFC3986 predicateTypes. These we will have to live with for a while :)
* We will have to go through our public documentation and make sure all the examples are correct.
> Deprecate short-names, and warn on non RFC3986 compliant predicate-types

- .github/workflows/release.yaml
- add new required input parameter
rehearsal here: https://github.com/cpanato/policy-controller/releases/tag/v99.99.04
Fixes: #638
> add new required input parameter

- .github/workflows/build.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/kind-cluster-image-policy-no-tuf.yaml
- .github/workflows/kind-cluster-image-policy-resync-period.yaml
- .github/workflows/kind-cluster-image-policy-trustroot.yaml
- .github/workflows/kind-cluster-image-policy-tsa.yaml
- .github/workflows/kind-cluster-image-policy.yaml
- .github/workflows/kind-e2e-cosigned.yaml
- .github/workflows/kind-e2e-trustroot-crd.yaml
- .github/workflows/policy-tester-examples.yml
- .github/workflows/release.yaml
- .github/workflows/style.yaml
- .github/workflows/tests.yaml
- .github/workflows/verify-codegen.yaml
- .github/workflows/verify-docs.yaml
- go.mod
> upgrade to use go1.20

- config/300-clusterimagepolicy.yaml
- docs/api-types/index-v1alpha1.md
- docs/api-types/index.md
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
For Static actions, they currently just say which CIP failed. To make the error message more actionable, add an optional Message field that then could contain suggestions for corrective actions.
* Add Message to static actions for more descriptive error messages.
*
> Add an optional Message to Static actions for custom fail message.

- cmd/tester/main.go
closes https://github.com/sigstore/policy-controller/issues/560
Load a trustroot definition using the policy-tester.
```
policy-tester \
--trustroot=trustroot.yaml \
--policy=test/testdata/policy-controller/tester/cip-public-keyless.yaml \
--image=k8s.gcr.io/pause:3.9
```
where the trustroot could be:
```yaml
apiVersion: policy.sigstore.dev/v1alpha1
kind: TrustRoot
metadata:
name: my-sigstore-keys
spec:
sigstoreKeys:
certificateAuthorities: []
timestampAuthorities:
- subject:
organization: tsa-organization
commonName: tsa-common-name
uri: TSA_URL
certChain: |-
TSA_CERT_CHAIN
...
```
> Load a TrustRoot reference when using the policy-tester

- pkg/policy/verifier.go
:bug: The policy tester library blindly checked the errors, but with multiple authorities we might have errors, but still successfully evaluated the policy.
Here is the comment from the ~equivalent call to `ValidatePolicy(` from `validator.go` for comparison:
```go
switch {
// Return AuthorityMatches before errors, since even if there
// are errors, if there are 0 or more authorities that match,
// it will pass the Policy. Of course, a CIP level policy can
// override this behaviour, but that has been checked above and
// if it failed, it will nil out the policyResult.
case result.policyResult != nil:
policyResults[result.name] = result.policyResult
case len(result.errors) > 0:
ret[result.name] = append(ret[result.name], result.errors...)
default:
ret[result.name] = …
```
> Fix: Have the policy-tester library check policy result.

- .gitignore
- release/ko-sign-release-images.sh
The release pipeline was broken https://github.com/sigstore/policy-controller/actions/runs/5321425956/jobs/9636506755.
fix: broken release pipeline expecting one more controller image to sign.
> fix: broken release pipeline

- pkg/webhook/validator.go
- pkg/webhook/validator_result.go
- pkg/webhook/validator_test.go
At the moment, we're adding the signature, payload and predicate type of the verified attestations. However we'd need the attestation digest to track to which attestations we're referring to.
Store the digest of each verified attestation in the PolicyAttestation object.
> Store the digest of each verified attestation in the PolicyAttestation object

- .github/workflows/kind-e2e-cosigned.yaml
- .github/workflows/kind-e2e-trustroot-crd.yaml
Remove support for Kubernetes v1.22.x
> ci: remove support for Kubernetes v1.22.x

- .gitignore
- cmd/tester/main.go
When using `policy-tester`, I noticed the tool always output debug level logging. I added an optional `log-level` flag that will default to Info level logging. I also updated the Info level output to include logs indicating to the user what part of the verification process the tool was on.
Old successful verification output:
```
$ ./policy-tester --policy=test/testdata/policy-controller/tester/cip-public-keyless.yaml --image=ghcr.io/sigstore/cosign/cosign:v1.12.1
2024-05-09T09:08:21.768-0600	DEBUG	webhook/validator.go:498	Checking Authority: authority-0
2024-05-09T09:08:24.479-0600	DEBUG	webhook/validator.go:806	validated signature for ghcr.io/sigstore/cosign/cosign:v1.12.1, got 1 signatures
2024-05-09T09:08:24.479-0600	DEBUG	webhook/validator.go:644	Converting signature &{b:[123 34 99 …
```
> Add `log-level` flag to policy-tester, update output

- .github/workflows/kind-cluster-image-policy-no-tuf.yaml
- .github/workflows/kind-cluster-image-policy-trustroot.yaml
- .github/workflows/kind-cluster-image-policy-tsa.yaml
- .github/workflows/kind-cluster-image-policy.yaml
Upgrade scaffolding to `v0.7.2` in the Kind related workflows. This will resolve the metallb related errors we are seeing in the Kind testing workflows.
> Upgrade scaffolding to v0.7.2

- pkg/webhook/registryauth/azure/acrhelper.go
This PR adds a check that will only run the ACR credential helper when the target registry is a subdomain of `azurecr.io`.
This is similar to an [existing check used for GCR](https://github.com/google/go-containerregistry/blob/main/pkg/v1/google/keychain.go#L62-L64).
Fixes https://github.com/sigstore/policy-controller/issues/1657
> Add check for ACR registry in ACR credential helper

- .github/workflows/kind-cluster-image-policy-no-tuf.yaml
- .github/workflows/kind-cluster-image-policy-trustroot.yaml
- .github/workflows/kind-cluster-image-policy-tsa.yaml
- .github/workflows/kind-cluster-image-policy.yaml
Remove old versions of k8s since they are no longer supported, we should not be testing with them.
Use new scaffolding version that support later versions of k8s.
> Use v0.7.18 for scaffolding, update k8s versions to test with.

- .github/workflows/release.yaml
see https://github.com/sigstore/policy-controller/actions/runs/12599069304/job/35116178539
to fix that we set the paralellism to 1, we did this in other pipelines
> fix goreleaser signning part

- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
This PR updates the code to preserve the original image tag when resolving image tags to digests in the mutating webhook.
Currently, the Sigstore Policy Controller's mutating webhook converts image references from `{registry}/{repository}:{tag}` to `{registry}/{repository}@sha256:{hash}`. This PR changes the behavior to convert them to `{registry}/{repository}:{tag}@sha256:{hash}` instead.
This change is considered to have no security concerns because when both a tag and a digest are specified for an image, the tag is ignored, and only the digest is used for image pulling and verification by container runtimes.
Preserving the image tag offers benefits such as:
* **Improved human readability:** Makes it easier to quickly identify which image version is being used.
* **Enhanced …
> Preserve original tag when resolving an image tag to digest

- cmd/webhook/main.go
- config/300-clusterimagepolicy.yaml
- docs/api-types/index-v1alpha1.md
- docs/api-types/index.md
- go.mod
- pkg/apis/policy/v1alpha1/clusterimagepolicy_conversion.go
- pkg/apis/policy/v1alpha1/clusterimagepolicy_types.go
- pkg/apis/policy/v1beta1/clusterimagepolicy_types.go
- pkg/reconciler/trustroot/controller.go
- pkg/reconciler/trustroot/controller_test.go
- pkg/tuf/context.go
- pkg/tuf/context_test.go
- pkg/tuf/repo.go
- pkg/webhook/clusterimagepolicy/clusterimagepolicy_types.go
- pkg/webhook/validator.go
- pkg/webhook/validator_test.go
This PR adds support for the [Cosign Bundle Spec](https://github.com/sigstore/cosign/blob/main/specs/BUNDLE_SPEC.md) for verifying attestations. This is compatible with the recently-introduced `--new-bundle-format` flag in `cosign attest`.
To enable, the `ClusterImagePolicy` authority section now includes a `SignatureFormat` field, which may be set to "bundle" in order to enable bundle verification.
> Add support for Sigstore Bundle Spec
